### ISSUE TITLE
PSQL Support ?

### ISSUE THREAD

**Issue by bheemreddy181** [macbre/index-digest#159]
Is there any support for PSQL ?

**Comment by macbre** [comment]
@bheemreddy181 - not at the moment, this tool is quite MySQL-specific. Are there any PostgreSQL-specific things you'd like this tool to check?

**Comment by bheemreddy181** [comment]
Hahaha I got a response after an year :) but well ya I was looking something specific for Postgres and we got that addressed with other tools like schemacrawler so we are good for now. I am closing this.
