### ISSUE TITLE
Report full table scan

### ISSUE THREAD

**Issue by gbenson-wikia** [macbre/index-digest#26]
A full table scan during a join is almost never what one would want, and is a good indicator of an opportunity to add better indexes and/or refactor the query.

**Comment by macbre** [comment]
> The output from EXPLAIN shows ALL in the type column when MySQL uses a full table scan to resolve a query. This usually happens under the following conditions:
>
> There are no usable restrictions in the ON or WHERE clause for indexed columns.
>
> https://dev.mysql.com/doc/refman/5.7/en/table-scan-avoidance.html
